- id: docker-phpda-0
  name: PHP Dependency Analysis in 'Classes'
  description: Run `phpda` to find possible cycles
  language: docker_image
  files: (source/Internal/Framework/Module/.+\.php)$
  entry: oxid/phpda:latest
  pass_filenames: false
  args: ["-q", "--", "/phpda/config/config_CLASS.yml"]

- id: docker-phpda-1
  name: PHP Dependency Analysis in 'Internal'
  description: Run `phpda` to find possible cycles
  language: docker_image
  files: (source/Internal/Framework/Module/.+\.php)$
  entry: oxid/phpda:latest
  pass_filenames: false
  args: ["-q", "--", "/phpda/config/config_PACKAGE_LVL_0.yml"]

- id: docker-phpda-2
  name: PHP Dependency Analysis in 'Domain/ & Framework/'
  description: Run `phpda` to find possible cycles
  language: docker_image
  files: (source/Internal/.+\.php)$
  entry: oxid/phpda:latest
  pass_filenames: false
  args: ["-q", "--", "/phpda/config/config_PACKAGE_LVL_1.yml"]

- id: docker-phpda-3
  name: PHP Dependency Analysis in 'Framework/Module'
  description: Run `phpda` to find possible cycles
  language: docker_image
  files: (source/Internal/Framework/Module/.+\.php)$
  entry: oxid/phpda:latest
  pass_filenames: false
  args: ["-q", "--", "/phpda/config/config_PACKAGE_LVL_2.yml"]

- id: container-factory-check
  name: Check 'ContainerFactory' used
  description: Check if 'ContainerFactory' class is used in source code
  language: script
  entry: pre_commit_hooks/check_string_occurrence.sh
  files: \.php$
  exclude: (source/Internal/Container/.+\.php|source/Core/.*)$
  args: ["--color=always", "-e", "ContainerFactory"]
