#config_PACKAGE_LVL_2.yml
mode: 'usage'
source: '/src/source/Internal/Framework/Module/**'
filePattern: '*.php'
formatter: 'PhpDA\Writer\Strategy\SVG_TXT_CLASS'
target: '/dev/null'
visitor:
 - PhpDA\Parser\Visitor\TagCollector
 - PhpDA\Parser\Visitor\SuperglobalCollector
visitorOptions:
 PhpDA\Parser\Visitor\Required\DeclaredNamespaceCollector: {minDepth: 5, sliceLength: 6}
 PhpDA\Parser\Visitor\Required\MetaNamespaceCollector: {minDepth: 5, sliceLength: 6}
 PhpDA\Parser\Visitor\Required\UsedNamespaceCollector: {minDepth: 5, sliceLength: 6}
 PhpDA\Parser\Visitor\TagCollector: {minDepth: 5, sliceLength: 6}
